//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonType
    {
        public PersonType()
        {
            this.WeddingPersons = new HashSet<WeddingPerson>();
        }
    
        public int ID { get; set; }
        public string PersonTypeDesc { get; set; }
    
        public virtual ICollection<WeddingPerson> WeddingPersons { get; set; }
    }
}
