//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeddingPerson
    {
        public WeddingPerson()
        {
            this.WeddingPerson1 = new HashSet<WeddingPerson>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string FacebookLink { get; set; }
        public string TwiiterLink { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> PersonTypeId { get; set; }
        public string Bio { get; set; }
        public Nullable<int> WeddingID { get; set; }
        public bool ShowFacebook { get; set; }
        public bool ShowTwitter { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string Email { get; set; }
        public string Cellphone { get; set; }
        public string GooglePlus { get; set; }
        public bool ShowGooglePlus { get; set; }
        public int GuestCount { get; set; }
        public string FirstGuestName { get; set; }
        public string FirstGuestSurname { get; set; }
    
        public virtual PersonType PersonType { get; set; }
        public virtual Wedding Wedding { get; set; }
        public virtual ICollection<WeddingPerson> WeddingPerson1 { get; set; }
        public virtual WeddingPerson WeddingPerson2 { get; set; }
    }
}
