//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wedding.logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeddingContext : DbContext
    {
        public WeddingContext()
            : base("name=WeddingContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Wedding> Weddings { get; set; }
        public DbSet<PersonType> PersonTypes { get; set; }
        public DbSet<WeddingPerson> WeddingPersons { get; set; }
        public DbSet<WeddingPhoto> WeddingPhotos { get; set; }
        public DbSet<WeddingSetting> WeddingSettings { get; set; }
    }
}
