//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wedding.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedding
    {
        public Wedding()
        {
            this.WeddingPersons = new HashSet<WeddingPerson>();
            this.WeddingPhotos = new HashSet<WeddingPhoto>();
            this.WeddingSettings = new HashSet<WeddingSetting>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Directions { get; set; }
        public string GoogleMapLink { get; set; }
        public string OurStory { get; set; }
        public string EventDetails { get; set; }
        public string Domain { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public bool ShowEvent { get; set; }
        public bool ShowStory { get; set; }
        public bool ShowDirections { get; set; }
    
        public virtual ICollection<WeddingPerson> WeddingPersons { get; set; }
        public virtual ICollection<WeddingPhoto> WeddingPhotos { get; set; }
        public virtual ICollection<WeddingSetting> WeddingSettings { get; set; }
    }
}
