//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wedding.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeddingSetting
    {
        public int ID { get; set; }
        public string InviteContentType { get; set; }
        public Nullable<long> InviteContentLength { get; set; }
        public byte[] InviteConentBody { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int WeddingID { get; set; }
        public string MailAddress { get; set; }
    
        public virtual Wedding Wedding { get; set; }
    }
}
